# Generated by Django 4.1.4 on 2022-12-08 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=100, verbose_name='Original word')),
                ('transcription', models.CharField(blank=True, max_length=100, null=True)),
                ('translation', models.CharField(max_length=100)),
                ('sentences', models.TextField(blank=True, max_length=500, null=True, verbose_name='Sentences for describing word')),
                ('notes', models.TextField(blank=True, max_length=500, null=True, verbose_name='Notes for additional information')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
