# Generated by Django 4.1.4 on 2022-12-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0002_word_ans_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('original_word',)},
        ),
    ]
