# Generated by Django 4.1.4 on 2022-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_muser_options_alter_muser_is_email_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='is_email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Has user confirmed email'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='is_user_premium',
            field=models.BooleanField(default=False, verbose_name='Has user premium'),
        ),
    ]
