# Generated by Django 4.1.4 on 2023-01-28 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_muser_is_email_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Confirmation token')),
            ],
        ),
    ]
