# Generated by Django 4.1.4 on 2022-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('word', '0003_alter_word_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title of card')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='Description of card')),
                ('words', models.ManyToManyField(related_name='cards', to='word.word')),
            ],
        ),
    ]
